version: '3.8'

services:

    # Nginx
    proxy:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        env_file: .env
        ports:
            - 80:80
            - 443:443
        depends_on:
            - frontend
            - backend
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - ft_42

    # VueJs - NodeJs
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        restart: always
        env_file: .env
        ports:
            - 5173:5173
        volumes:
            - ./frontend:/app
        networks:
            - ft_42

    # NestJs - NodeJs
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        restart: always
        env_file: .env
        ports:
            - 3000:3000
        volumes:
            - ./backend:/app
        networks:
            - ft_42

    # PostgresSql - Database
    database:
        build:
            context: ./database
            dockerfile: Dockerfile
        container_name: database
        restart: always
        env_file: .env
        volumes:
            - database:/var/lib/postgresql/data
        networks:
            - ft_42

# Volumes
volumes:
    database:

# Networks
networks:
    ft_42:
        driver: bridge
