version: "3.8"

networks:
  trantran: {}

services:
  server:
    container_name: nginx
    build:
      context: ./nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - './nginx/certs:/certs'
    ports:
      - '8443:443'
      - '8080:80'
    networks:
      - trantran

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - './frontend:/app'
    working_dir: /app
    networks:
      - trantran
      
  # Nestjs backend
  backend:
    container_name: backend
    restart: always
    build:
        context: ./backend
    depends_on:
      - db
    env_file: 
      - ./backend/.env
    expose: 
      - '4000'
    networks:
      - trantran
  
  #Postgresql database
  db:
    image:  postgres:15.1-alpine
    container_name: db
    env_file: 
      - ./backend/.env
    restart: always
    volumes:
      - 'database:/var/lib/postgresql/data'
    networks:
      - trantran



volumes:
  database:
  frontend_modules:
